<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule\Helper;

use Zikula\TrivialModule\Helper\Base\AbstractEntityDisplayHelper;

/**
 * Entity display helper implementation class.
 */
class EntityDisplayHelper extends AbstractEntityDisplayHelper
{
    // feel free to extend the entity display helper here
}
