<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule\Helper\Base;

use IntlDateFormatter;
use Symfony\Component\HttpFoundation\RequestStack;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\TrivialModule\Entity\TournamentEntity;
use Zikula\TrivialModule\Entity\QuestionEntity;
use Zikula\TrivialModule\Entity\AnswerEntity;
use Zikula\TrivialModule\Entity\ResultEntity;
use Zikula\TrivialModule\Helper\ListEntriesHelper;

/**
 * Entity display helper base class.
 */
abstract class AbstractEntityDisplayHelper
{
    /**
     * @var TranslatorInterface
     */
    protected $translator;

    /**
     * @var ListEntriesHelper Helper service for managing list entries
     */
    protected $listEntriesHelper;

    /**
     * @var IntlDateFormatter Formatter for dates
     */
    protected $dateFormatter;

    /**
     * EntityDisplayHelper constructor.
     *
     * @param TranslatorInterface $translator        Translator service instance
     * @param RequestStack        $requestStack      RequestStack service instance
     * @param ListEntriesHelper   $listEntriesHelper Helper service for managing list entries
     */
    public function __construct(
        TranslatorInterface $translator,
        RequestStack $requestStack,
        ListEntriesHelper $listEntriesHelper
    ) {
        $this->translator = $translator;
        $this->listEntriesHelper = $listEntriesHelper;
        $locale = null !== $requestStack->getCurrentRequest() ? $requestStack->getCurrentRequest()->getLocale() : null;
        $this->dateFormatter = new IntlDateFormatter($locale, IntlDateFormatter::NONE, IntlDateFormatter::NONE);
    }

    /**
     * Returns the formatted title for a given entity.
     *
     * @param object $entity The given entity instance
     *
     * @return string The formatted title
     */
    public function getFormattedTitle($entity)
    {
        if ($entity instanceof TournamentEntity) {
            return $this->formatTournament($entity);
        }
        if ($entity instanceof QuestionEntity) {
            return $this->formatQuestion($entity);
        }
        if ($entity instanceof AnswerEntity) {
            return $this->formatAnswer($entity);
        }
        if ($entity instanceof ResultEntity) {
            return $this->formatResult($entity);
        }
    
        return '';
    }
    
    /**
     * Returns the formatted title for a given entity.
     *
     * @param TournamentEntity $entity The given entity instance
     *
     * @return string The formatted title
     */
    protected function formatTournament(TournamentEntity $entity)
    {
        return $this->translator->__f('%name%', [
            '%name%' => $entity->getName()
        ]);
    }
    
    /**
     * Returns the formatted title for a given entity.
     *
     * @param QuestionEntity $entity The given entity instance
     *
     * @return string The formatted title
     */
    protected function formatQuestion(QuestionEntity $entity)
    {
        return $this->translator->__('Question');
    }
    
    /**
     * Returns the formatted title for a given entity.
     *
     * @param AnswerEntity $entity The given entity instance
     *
     * @return string The formatted title
     */
    protected function formatAnswer(AnswerEntity $entity)
    {
        return $this->translator->__('Answer');
    }
    
    /**
     * Returns the formatted title for a given entity.
     *
     * @param ResultEntity $entity The given entity instance
     *
     * @return string The formatted title
     */
    protected function formatResult(ResultEntity $entity)
    {
        return $this->translator->__('Result');
    }
    
    /**
     * Returns name of the field used as title / name for entities of this repository.
     *
     * @param string $objectType Name of treated entity type
     *
     * @return string Name of field to be used as title
     */
    public function getTitleFieldName($objectType)
    {
        if ($objectType == 'tournament') {
            return 'name';
        }
        if ($objectType == 'question') {
            return 'question';
        }
        if ($objectType == 'answer') {
            return 'answer';
        }
        if ($objectType == 'result') {
            return '';
        }
    
        return '';
    }
    
    /**
     * Returns name of the field used for describing entities of this repository.
     *
     * @param string $objectType Name of treated entity type
     *
     * @return string Name of field to be used as description
     */
    public function getDescriptionFieldName($objectType)
    {
        if ($objectType == 'tournament') {
            return 'name';
        }
        if ($objectType == 'question') {
            return 'question';
        }
        if ($objectType == 'answer') {
            return 'answer';
        }
        if ($objectType == 'result') {
            return '';
        }
    
        return '';
    }
    
    /**
     * Returns name of the date(time) field to be used for representing the start
     * of this object. Used for providing meta data to the tag module.
     *
     * @param string $objectType Name of treated entity type
     *
     * @return string Name of field to be used as date
     */
    public function getStartDateFieldName($objectType)
    {
        if ($objectType == 'tournament') {
            return 'createdDate';
        }
        if ($objectType == 'question') {
            return 'createdDate';
        }
        if ($objectType == 'answer') {
            return 'createdDate';
        }
        if ($objectType == 'result') {
            return 'createdDate';
        }
    
        return '';
    }
}
