services:
    zikula_trivial_module.link_container:
        class: Zikula\TrivialModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_trivial_module.controller_helper"
        tags: ['zikula.link_container']
