services:
    # Custom validators
    zikula_trivial_module.validator.list_entry.validator:
        class: Zikula\TrivialModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@zikula_trivial_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: zikula_trivial_module.validator.list_entry.validator }
