<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule\Form\Type;

use Zikula\TrivialModule\Form\Type\Base\AbstractAnswerType;

/**
 * Answer editing form type implementation class.
 */
class AnswerType extends AbstractAnswerType
{
    // feel free to extend the answer editing form type class here
}
