<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule;

use Zikula\TrivialModule\Base\AbstractAppSettings;

/**
 * Application settings class for handling module variables.
 */
class AppSettings extends AbstractAppSettings
{
    // feel free to add your own methods here
}
