<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule\Event;

use Zikula\TrivialModule\Event\Base\AbstractFilterAnswerEvent;

/**
 * Event implementation class for filtering answer processing.
 */
class FilterAnswerEvent extends AbstractFilterAnswerEvent
{
    // feel free to extend the event class here
}
