<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule\Entity;

use Zikula\TrivialModule\Entity\Base\AbstractQuestionCategoryEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing question categories.
 *
 * This is the concrete category class for question entities.
 * @ORM\Entity(repositoryClass="\Zikula\TrivialModule\Entity\Repository\QuestionCategoryRepository")
 * @ORM\Table(name="zikula_trivial_question_category",
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="cat_unq", columns={"registryId", "categoryId", "entityId"})
 *     }
 * )
 */
class QuestionCategoryEntity extends BaseEntity
{
    // feel free to add your own methods here
}
