<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule\Form\Type\Field;

use Zikula\TrivialModule\Form\Type\Field\Base\AbstractMultiListType;

/**
 * Multi list field type implementation class.
 */
class MultiListType extends AbstractMultiListType
{
    // feel free to extend the base form type class here
}
