<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule\Form\Handler\Tournament;

use Zikula\TrivialModule\Form\Handler\Tournament\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of editing forms.
 * It aims on the tournament object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
