<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule\DependencyInjection;

use Zikula\TrivialModule\DependencyInjection\Base\AbstractZikulaTrivialExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class ZikulaTrivialExtension extends AbstractZikulaTrivialExtension
{
    // custom enhancements can go here
}
