<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule\HookSubscriber;

use Zikula\TrivialModule\HookSubscriber\Base\AbstractAnswerFormAwareHookSubscriber;

/**
 * Implementation class for form aware hook subscriber.
 */
class AnswerFormAwareHookSubscriber extends AbstractAnswerFormAwareHookSubscriber
{
    // feel free to add your own convenience methods here
}
