<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule\Entity\Base;

use Doctrine\ORM\Mapping as ORM;
use Zikula\CategoriesModule\Entity\AbstractCategoryAssignment;

/**
 * Entity extension domain class storing question categories.
 *
 * This is the base category class for question entities.
 */
abstract class AbstractQuestionCategoryEntity extends AbstractCategoryAssignment
{
    /**
     * @ORM\ManyToOne(targetEntity="\Zikula\TrivialModule\Entity\QuestionEntity", inversedBy="categories")
     * @ORM\JoinColumn(name="entityId", referencedColumnName="id")
     * @var \Zikula\TrivialModule\Entity\QuestionEntity
     */
    protected $entity;
    
    /**
     * Get reference to owning entity.
     *
     * @return \Zikula\TrivialModule\Entity\QuestionEntity
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Set reference to owning entity.
     *
     * @param \Zikula\TrivialModule\Entity\QuestionEntity $entity
     */
    public function setEntity(/*\Zikula\TrivialModule\Entity\QuestionEntity */$entity)
    {
        $this->entity = $entity;
    }
}
