<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use Zikula\TrivialModule\Entity\QuestionEntity;

/**
 * Event base class for filtering question processing.
 */
class AbstractFilterQuestionEvent extends Event
{
    /**
     * @var QuestionEntity Reference to treated entity instance.
     */
    protected $question;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterQuestionEvent constructor.
     *
     * @param QuestionEntity $question Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(QuestionEntity $question, array $entityChangeSet = [])
    {
        $this->question = $question;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return QuestionEntity
     */
    public function getQuestion()
    {
        return $this->question;
    }

    /**
     * Returns the change set.
     *
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
