<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule\Container\Base;

use Symfony\Component\Routing\RouterInterface;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Zikula\Core\Doctrine\EntityAccess;
use Zikula\Core\LinkContainer\LinkContainerInterface;
use Zikula\ExtensionsModule\Api\ApiInterface\VariableApiInterface;
use Zikula\PermissionsModule\Api\ApiInterface\PermissionApiInterface;
use Zikula\TrivialModule\Helper\ControllerHelper;

/**
 * This is the link container service implementation class.
 */
abstract class AbstractLinkContainer implements LinkContainerInterface
{
    use TranslatorTrait;

    /**
     * @var RouterInterface
     */
    protected $router;

    /**
     * @var PermissionApiInterface
     */
    protected $permissionApi;

    /**
     * @var VariableApiInterface
     */
    protected $variableApi;

    /**
     * @var ControllerHelper
     */
    protected $controllerHelper;

    /**
     * LinkContainer constructor.
     *
     * @param TranslatorInterface    $translator       Translator service instance
     * @param Routerinterface        $router           Router service instance
     * @param PermissionApiInterface $permissionApi    PermissionApi service instance
     * @param VariableApiInterface   $variableApi      VariableApi service instance
     * @param ControllerHelper       $controllerHelper ControllerHelper service instance
     */
    public function __construct(
        TranslatorInterface $translator,
        RouterInterface $router,
        PermissionApiInterface $permissionApi,
        VariableApiInterface $variableApi,
        ControllerHelper $controllerHelper
    ) {
        $this->setTranslator($translator);
        $this->router = $router;
        $this->permissionApi = $permissionApi;
        $this->variableApi = $variableApi;
        $this->controllerHelper = $controllerHelper;
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

    /**
     * Returns available header links.
     *
     * @param string $type The type to collect links for
     *
     * @return array List of header links
     */
    public function getLinks($type = LinkContainerInterface::TYPE_ADMIN)
    {
        $contextArgs = ['api' => 'linkContainer', 'action' => 'getLinks'];
        $allowedObjectTypes = $this->controllerHelper->getObjectTypes('api', $contextArgs);

        $permLevel = LinkContainerInterface::TYPE_ADMIN == $type ? ACCESS_ADMIN : ACCESS_READ;

        // Create an array of links to return
        $links = [];

        if (LinkContainerInterface::TYPE_ACCOUNT == $type) {
            if (!$this->permissionApi->hasPermission($this->getBundleName() . '::', '::', ACCESS_OVERVIEW)) {
                return $links;
            }

            if (true === $this->variableApi->get('ZikulaTrivialModule', 'linkOwnTournamentsOnAccountPage', true)) {
                $objectType = 'tournament';
                if ($this->permissionApi->hasPermission($this->getBundleName() . ':' . ucfirst($objectType) . ':', '::', ACCESS_READ)) {
                    $links[] = [
                        'url' => $this->router->generate('zikulatrivialmodule_' . strtolower($objectType) . '_view', ['own' => 1]),
                        'text' => $this->__('My tournaments', 'zikulatrivialmodule'),
                        'icon' => 'list-alt'
                    ];
                }
            }

            if (true === $this->variableApi->get('ZikulaTrivialModule', 'linkOwnQuestionsOnAccountPage', true)) {
                $objectType = 'question';
                if ($this->permissionApi->hasPermission($this->getBundleName() . ':' . ucfirst($objectType) . ':', '::', ACCESS_READ)) {
                    $links[] = [
                        'url' => $this->router->generate('zikulatrivialmodule_' . strtolower($objectType) . '_view', ['own' => 1]),
                        'text' => $this->__('My questions', 'zikulatrivialmodule'),
                        'icon' => 'list-alt'
                    ];
                }
            }

            if (true === $this->variableApi->get('ZikulaTrivialModule', 'linkOwnAnswersOnAccountPage', true)) {
                $objectType = 'answer';
                if ($this->permissionApi->hasPermission($this->getBundleName() . ':' . ucfirst($objectType) . ':', '::', ACCESS_READ)) {
                    $links[] = [
                        'url' => $this->router->generate('zikulatrivialmodule_' . strtolower($objectType) . '_view', ['own' => 1]),
                        'text' => $this->__('My answers', 'zikulatrivialmodule'),
                        'icon' => 'list-alt'
                    ];
                }
            }

            if (true === $this->variableApi->get('ZikulaTrivialModule', 'linkOwnResultsOnAccountPage', true)) {
                $objectType = 'result';
                if ($this->permissionApi->hasPermission($this->getBundleName() . ':' . ucfirst($objectType) . ':', '::', ACCESS_READ)) {
                    $links[] = [
                        'url' => $this->router->generate('zikulatrivialmodule_' . strtolower($objectType) . '_view', ['own' => 1]),
                        'text' => $this->__('My results', 'zikulatrivialmodule'),
                        'icon' => 'list-alt'
                    ];
                }
            }

            if ($this->permissionApi->hasPermission($this->getBundleName() . '::', '::', ACCESS_ADMIN)) {
                $links[] = [
                    'url' => $this->router->generate('zikulatrivialmodule_tournament_adminindex'),
                    'text' => $this->__('Trivial Backend', 'zikulatrivialmodule'),
                    'icon' => 'wrench'
                ];
            }


            return $links;
        }

        $routeArea = LinkContainerInterface::TYPE_ADMIN == $type ? 'admin' : '';
        if (LinkContainerInterface::TYPE_ADMIN == $type) {
            if ($this->permissionApi->hasPermission($this->getBundleName() . '::', '::', ACCESS_READ)) {
                $links[] = [
                    'url' => $this->router->generate('zikulatrivialmodule_tournament_index'),
                    'text' => $this->__('Frontend', 'zikulatrivialmodule'),
                    'title' => $this->__('Switch to user area.', 'zikulatrivialmodule'),
                    'icon' => 'home'
                ];
            }
        } else {
            if ($this->permissionApi->hasPermission($this->getBundleName() . '::', '::', ACCESS_ADMIN)) {
                $links[] = [
                    'url' => $this->router->generate('zikulatrivialmodule_tournament_adminindex'),
                    'text' => $this->__('Backend', 'zikulatrivialmodule'),
                    'title' => $this->__('Switch to administration area.', 'zikulatrivialmodule'),
                    'icon' => 'wrench'
                ];
            }
        }
        
        if (in_array('tournament', $allowedObjectTypes)
            && $this->permissionApi->hasPermission($this->getBundleName() . ':Tournament:', '::', $permLevel)) {
            $links[] = [
                'url' => $this->router->generate('zikulatrivialmodule_tournament_' . $routeArea . 'view'),
                'text' => $this->__('Tournaments', 'zikulatrivialmodule'),
                'title' => $this->__('Tournaments list', 'zikulatrivialmodule')
            ];
        }
        if (in_array('question', $allowedObjectTypes)
            && $this->permissionApi->hasPermission($this->getBundleName() . ':Question:', '::', $permLevel)) {
            $links[] = [
                'url' => $this->router->generate('zikulatrivialmodule_question_' . $routeArea . 'view'),
                'text' => $this->__('Questions', 'zikulatrivialmodule'),
                'title' => $this->__('Questions list', 'zikulatrivialmodule')
            ];
        }
        if (in_array('answer', $allowedObjectTypes)
            && $this->permissionApi->hasPermission($this->getBundleName() . ':Answer:', '::', $permLevel)) {
            $links[] = [
                'url' => $this->router->generate('zikulatrivialmodule_answer_' . $routeArea . 'view'),
                'text' => $this->__('Answers', 'zikulatrivialmodule'),
                'title' => $this->__('Answers list', 'zikulatrivialmodule')
            ];
        }
        if (in_array('result', $allowedObjectTypes)
            && $this->permissionApi->hasPermission($this->getBundleName() . ':Result:', '::', $permLevel)) {
            $links[] = [
                'url' => $this->router->generate('zikulatrivialmodule_result_' . $routeArea . 'view'),
                'text' => $this->__('Results', 'zikulatrivialmodule'),
                'title' => $this->__('Results list', 'zikulatrivialmodule')
            ];
        }
        if ($routeArea == 'admin' && $this->permissionApi->hasPermission($this->getBundleName() . '::', '::', ACCESS_ADMIN)) {
            $links[] = [
                'url' => $this->router->generate('zikulatrivialmodule_config_config'),
                'text' => $this->__('Configuration', 'zikulatrivialmodule'),
                'title' => $this->__('Manage settings for this application', 'zikulatrivialmodule'),
                'icon' => 'wrench'
            ];
        }

        return $links;
    }

    /**
     * Returns the name of the providing bundle.
     *
     * @return string The bundle name
     */
    public function getBundleName()
    {
        return 'ZikulaTrivialModule';
    }
}
