<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule\Form\DataTransformer;

use Zikula\TrivialModule\Form\DataTransformer\Base\AbstractListFieldTransformer;

/**
 * List field transformer implementation class.
 *
 * This data transformer treats multi-valued list fields.
 */
class ListFieldTransformer extends AbstractListFieldTransformer
{
    // feel free to add your customisation here
}
