<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule\Validator\Constraints;

use Zikula\TrivialModule\Validator\Constraints\Base\AbstractListEntry;

/**
 * List entry validation constraint.
 *
 * @Annotation
 */
class ListEntry extends AbstractListEntry
{
    // here you can customise the constraint
}
