<?php
/**
 * Trivial.
 *
 * @copyright Krator (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Krator <kratord@hotmail.com>.
 * @link https://www.heroesofmightandmagic.es
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.2.0 (https://modulestudio.de).
 */

namespace Zikula\TrivialModule\Entity\Factory\Base;

use Zikula\TrivialModule\Entity\TournamentEntity;
use Zikula\TrivialModule\Entity\QuestionEntity;
use Zikula\TrivialModule\Entity\AnswerEntity;
use Zikula\TrivialModule\Entity\ResultEntity;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * Initialises a given tournament instance.
     *
     * @param TournamentEntity $entity The newly created entity instance
     *
     * @return TournamentEntity The updated entity instance
     */
    public function initTournament(TournamentEntity $entity)
    {

        return $entity;
    }

    /**
     * Initialises a given question instance.
     *
     * @param QuestionEntity $entity The newly created entity instance
     *
     * @return QuestionEntity The updated entity instance
     */
    public function initQuestion(QuestionEntity $entity)
    {

        return $entity;
    }

    /**
     * Initialises a given answer instance.
     *
     * @param AnswerEntity $entity The newly created entity instance
     *
     * @return AnswerEntity The updated entity instance
     */
    public function initAnswer(AnswerEntity $entity)
    {

        return $entity;
    }

    /**
     * Initialises a given result instance.
     *
     * @param ResultEntity $entity The newly created entity instance
     *
     * @return ResultEntity The updated entity instance
     */
    public function initResult(ResultEntity $entity)
    {

        return $entity;
    }

}
